# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Python技术', 'Python技术'), ('数据库技术', '数据库技术'), ('经济学', '经济学'), ('文体咨询', '文体咨询'), ('个人心情', '个人心情'), ('其他', '其他')], default=('Python技术', 'Python技术'), max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='user_name',
            field=models.CharField(default='匿名', max_length=20),
        ),
    ]
